name: Daily Email Digest

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: Default

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: pip install groq python-dotenv

      - name: Setup Composio
        run: |
          npm install -g composio
          export PATH="$PATH:$(npm root -g)/.bin"
          composio login --api-key ${{ vars.COMPOSIO_API_KEY }}
          composio whoami

      - name: Set env
        run: echo "GROQ_API_KEY=${{ vars.GROQ_API_KEY }}" >> .env

      - name: Run script
        run: python mail.py